version: "3.5"

services:
  authentication-service:
    container_name: authentication-service_api
    build:
      context: ./
      dockerfile: Dockerfile
    image: authentication-service
    ports:
      - "8081:8080"
    depends_on:
      - authentication-service_database
    networks:
      - noodlee-system-network

  authentication-service_database:
    container_name: authentication-service_database
    image: postgres:9.6
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PdgDNLnlrr3NgshqwKJA
      POSTGRES_DB: registration
    volumes:
      - authentication-service_database-volume:/var/lib/postgresql/gateway
      - ./_database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - noodlee-system-network

networks:
  noodlee-system-network:
    name: noodlee-system-network
    driver: bridge
    
volumes:
  authentication-service_database-volume:
